# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - learn-bot

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://learnbotcontainer.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_5b085112085a4aeeb1112f5cab2c4e76 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_d65a72a92adb45fdabf062be6a2650be }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: learnbotcontainer.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_5b085112085a4aeeb1112f5cab2c4e76 }}/learnbot:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'learn-bot'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_96998cc27195413d88701df4fc2ee9d6 }}
        images: 'learnbotcontainer.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_5b085112085a4aeeb1112f5cab2c4e76 }}/learnbot:${{ github.sha }}'